import Head from "next/head";
import Image from "next/image";
import useCourses from "../lib/hooks/useCourses"
import useAssignments from "../lib/hooks/useAssignments"

import { useEffect } from "react";

const Home = () => {
  const { courses } = useCourses()
  const { assignments } = useAssignments()

  useEffect(() => {
    console.log(courses)
    console.log(assignments)

  }, [courses, assignments])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="font-bold text-3xl">Start project</h1>
    </>
  );
};

export default Home;
