import Head from "next/head";
import Image from "next/image";
import Explore from "../components/CourseSelection/Explore"

const Home = () => {
  return (
    <>
      <Head>
        <title>PSE-E</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Explore />
    </>
  );
};

export default Home;
