import Head from "next/head";
import Image from "next/image";
import NavBar from "../../../../../components/NavBar";
import { useRouter } from "next/router";
import React, { useState } from "react";
import Link from 'next/link';

interface ContentItem {
  id: number;
  label: string;
  content: string
}

const Assignments = () => {
  const router = useRouter();
  const { courseId: courseId, assignmentId: assignmentId } = router.query;

  const [selectedLink, setSelectedLink] = useState<number>(1);

  const assignmentContent: ContentItem[] = [
    { id: 1, label: "Description", content: "Content description" }
    // { id: 2, label: "Rubric", content: "Content rubric" },
  ];

  const handleLinkClick = (linkId: number) => {
    setSelectedLink(linkId);
  };

  return (
    <>
      <Head>
        <title>Assignments - WriteSpace</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar />

      <div className="bg-gray-50 min-h-screen py-10 mt-12">
        <div className="max-w-5xl mx-auto px-6">
          <div className="flex items-center justify-between mb-6">
            <h1 className="text-3xl font-bold">Assignments</h1>
            <div className="space-x-4">
              <p className="mt-8 text-gray-600">Deadline: June 30, 2023</p>
            </div>
          </div>

          <div className="grid grid-cols-1 gap-0 md:grid-cols-5 ">
            <div className="col-span-1 p-4">
              <div className="w-full p-4 bg-white rounded-lg shadow-lg">
                {assignmentContent.map((obj) => (
                  <div key={obj.id}>
                    <button
                      onClick={() => handleLinkClick(obj.id)}
                      className={`text-sm text-gray-500 underline cursor-pointer ${selectedLink === obj.id ? "font-bold" : ""
                        }`}
                    >
                      {obj.label}
                    </button>
                  </div>
                ))}
              </div>
            </div>
            <div className="col-span-3 p-4">
              <div className="w-full p-4 bg-white rounded-lg shadow-lg ">
                <div className="flex space-x-4">
                  {assignmentContent.map((obj) => (
                    selectedLink === obj.id && (
                      <p key={obj.id} className="text-lg text-gray-800">
                        {obj.content}
                      </p>
                    )
                  ))}
                </div>
              </div>
            </div>
            <div className="col-span-1 p-4 ">
              <div className="w-full p-4 bg-white rounded-lg shadow-lg">
                {/* <div className="text-sm text-gray-500">Right Box</div> */}
                <div className="flex flex-col mt-4">
                  {/* <button className="block w-full py-2 px-4 bg-yellow-500 text-white rounded-md">
                    Upload file
                  </button> */}
                  <Link
                    href={`/courses/${courseId}/assignment/${assignmentId}/submission`}
                  >
                    <button className="block w-full py-2 px-4 bg-yellow-500 text-white rounded-md mt-2">
                      View submission
                    </button>
                  </Link>
                </div>
              </div>
            </div>
          </div>






        </div>
      </div>
    </>
  );
};

export default Assignments;
