import Head from "next/head";
import NavBar from "@/components/NavBar";
import { useRouter } from "next/router";
import React, { useContext, useEffect, useState } from "react";
import useAssignment from "@/lib/hooks/useAssignment";
import useAuthentication from "@/lib/hooks/useAuthentication";
import { formatDate } from "@/lib/date";
import { motion } from "framer-motion";
import useSubmission from "@/lib/hooks/useSubmission";

const Assignments = () => {
    const router = useRouter();
    // Accessing query parameters from the router object
    const { assignmentId } = router.query;
    const { token } = useAuthentication();
    const { assignment, getAssignment } = useAssignment(token, "", assignmentId?.toString()); // When navigating to a course via url
    const { submission, submissions } = useSubmission(token, assignmentId?.toString())

    useEffect(() => {
        console.log(submissions)
    }, [submissions]);

    return (
        <>
            <Head>
                <title>Assignment - WriteSpace</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <NavBar />

            <div className="bg-gray-50 py-10 mt-16 min-h-screen">
                <div className="text-center mb-6">
                    <motion.h1 layoutId={assignment?.name} className="text-3xl font-bold">{assignment?.name}</motion.h1>

                    <motion.div layoutId={assignment?.due_at?.toString()}>
                        <p className="mt-8 text-gray-600">
                            <span className="font-bold">Deadline: </span> {assignment?.due_at ? formatDate(assignment?.due_at) : "No due date"}</p>
                    </motion.div>
                </div>

                <div className="max-w-5xl mx-auto">
                    <div className="w-full relative overflow-x-auto shadow-md mt-4 ">
                        <table className="w-full text-sm text-left bg-white">
                            <thead className="text-xs text-gray-700 uppercase bg-gray-100 dark:bg-gray-700 dark:text-gray-400">
                                <tr>
                                    <th scope="col" className="px-6 py-4 whitespace-nowrap">
                                        Name
                                    </th>
                                    <th scope="col" className="px-6 py-4 whitespace-nowrap">
                                        Submission Status
                                    </th>
                                    <th scope="col" className="px-6 py-4 whitespace-nowrap">
                                        Grade Status
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                {submissions && submissions.map((submission, index) => (
                                    <tr
                                        key={index}
                                        className="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600"
                                    >
                                        <td className="px-6 py-4 whitespace-nowrap">
                                            {submission.userId}
                                        </td>
                                        <td className="px-6 py-4 whitespace-nowrap text-green-500 font-bold">
                                        </td>
                                        <td className="px-6 py-4 whitespace-nowrap">
                                        </td>
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </>
    );
};

export default Assignments;
