name: lighthouse benchmark
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  lighthouse:
    name: Run lighthouse benchmark
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v3

      - name: Install packages
        run: cd ./frontend-pse-e && npm build

      - name: Run lighthouse
        run: cd ./frontend-pse-e && npm run lighthouse:ci
