name: linter

on: push 

jobs:
  eslint:
   name: Linter code base 
   runs-on: ubuntu-latest

   steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Install packages backend
      run: cd backend && npm install
    
    - name: Run Eslint
      run: cd backend && npm run lint