name: backendCI

on:
  push:
    branches-ignore:
      - '*'
    paths-ignore:
      - 'frontend-pse-e/**'
  pull_request:
    branches:
      - backend
    types:
      - closed

jobs:
  backend_CI:
    name: Lint/test backend code base
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/backend/') || github.event_name == 'merge'

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v3

      - name: Install packages backend
        run: cd ./backend-pse-e && npm ci

      - name: Run Eslint
        run: cd ./backend-pse-e && npm run lint:ci

      - name: Run Tests
        run: cd ./backend-pse-e && npm run test:ci
