name: CI

on: push 

jobs:
  eslint:
   name: Lint code base 
   runs-on: ubuntu-latest

   steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v3
    
    - name: Install packages backend
      run: cd ./backend-pse-e && npm install
    
    - name: Run Eslint
      run: cd ./backend-pse-e && npm run lint:ci
    
      